"""
Esquemas Pydantic de la plataforma SynkData.

Centraliza la importación de todos los esquemas para facilitar
su uso en los routers y servicios de la aplicación.
"""

from app.schemas.verification import (
    ConsistencyResult,
    CurpCandidate,
    CurpExtractedInfo,
    CurpSearchRequest,
    CurpValidateRequest,
    CurpValidationResult,
    RfcExtractedInfo,
    RfcValidateRequest,
    RfcValidationResult,
    RfcVerifySatRequest,
    SatStatus,
    VerificationResponse,
    VerifyRequest,
)
from app.schemas.screening import (
    DofResultSchema,
    MatchDetailSchema,
    MatchTypeSchema,
    PepRequest,
    PepResultSchema,
    RiskLevelSchema,
    Sat69bRequest,
    Sat69bResultSchema,
    ScreeningEntityRequest,
    ScreeningPersonRequest,
    ScreeningRequestDetail,
    ScreeningResultSchema,
    ScjnResultSchema,
)
from app.schemas.identity import (
    CorrelationResult,
    CorrelationSignal,
    FullIdentityResponse,
    IdentityCorrelationDetail,
    IdentityData,
    MitigatingFactor,
    Recommendation,
    RiskAssessmentDetail,
    RiskAssessmentResult,
    RiskContext,
    RiskFactor,
    ScoreContributor,
    Severity,
    SocialProfileInput,
    TrustContext,
    TrustLevel,
    TrustScoreResult,
)

__all__ = [
    # Verification schemas
    "ConsistencyResult",
    "CurpCandidate",
    "CurpExtractedInfo",
    "CurpSearchRequest",
    "CurpValidateRequest",
    "CurpValidationResult",
    "RfcExtractedInfo",
    "RfcValidateRequest",
    "RfcValidationResult",
    "RfcVerifySatRequest",
    "SatStatus",
    "VerificationResponse",
    "VerifyRequest",
    # Screening schemas
    "DofResultSchema",
    "MatchDetailSchema",
    "MatchTypeSchema",
    "PepRequest",
    "PepResultSchema",
    "RiskLevelSchema",
    "Sat69bRequest",
    "Sat69bResultSchema",
    "ScreeningEntityRequest",
    "ScreeningPersonRequest",
    "ScreeningRequestDetail",
    "ScreeningResultSchema",
    "ScjnResultSchema",
    # Identity schemas
    "CorrelationResult",
    "CorrelationSignal",
    "FullIdentityResponse",
    "IdentityCorrelationDetail",
    "IdentityData",
    "MitigatingFactor",
    "Recommendation",
    "RiskAssessmentDetail",
    "RiskAssessmentResult",
    "RiskContext",
    "RiskFactor",
    "ScoreContributor",
    "Severity",
    "SocialProfileInput",
    "TrustContext",
    "TrustLevel",
    "TrustScoreResult",
]
